# Site settings
title: Alex Jiang
header-img: img/home-bg.jpg
email: alex.jiang@sportsbet.com.au
description: "Web, iOS, Design, Literature"
baseurl: ""
url: "https://pigfly.github.io"
timezone: Australia/Victoria
excerpt_separator: <!--more-->

# social media
twitter_username:
github_username:  pigfly
facebook_username:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 3
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Gems
gems: [jekyll-paginate, pygments.rb, jekyll-gist, less, therubyracer, rouge]
